//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testsite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities1 : DbContext
    {
        public DatabaseEntities1()
            : base("name=DatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LoginInfo> LoginInfoes { get; set; }
        public virtual DbSet<PictureContent> PictureContents { get; set; }
        public virtual DbSet<PictureMetadata> PictureMetadatas { get; set; }
        public virtual DbSet<postContent> postContents { get; set; }
        public virtual DbSet<postmetadata> postmetadatas { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
    }
}
