//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class PictureContent
    {
        public int PicContentId { get; set; }
        public Nullable<int> PicId { get; set; }
        public string Caption { get; set; }
        public string Path { get; set; }
        public string PictureFileName { get; set; }
        public string PicThumbnailPath { get; set; }
        public string takenBy { get; set; }
    
        public virtual PictureMetadata PictureMetadata { get; set; }
    }
}
