//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class PictureMetadata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PictureMetadata()
        {
            this.PictureContents = new HashSet<PictureContent>();
        }
    
        public int PicId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> fileSize { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Width { get; set; }
        public string Format { get; set; }
        public Nullable<int> picturePriority { get; set; }
        public Nullable<bool> isPostBackground { get; set; }
        public Nullable<bool> isPostMainPicture { get; set; }
        public Nullable<int> AssociatedPostId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PictureContent> PictureContents { get; set; }
        public virtual postmetadata postmetadata { get; set; }
    }
}
