//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.Tags = new HashSet<Tag>();
        }
    
        public int userId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public int NoOfPosts { get; set; }
        public int NoOfTags { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public bool isAuthor { get; set; }
        public int AdminId { get; set; }
        public bool isAdmin { get; set; }
    
        public virtual LoginInfo LoginInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
